 name: JSDoc to pages
 on: 
   push:
     branches:
       - master

 jobs:
 
   build:
     runs-on: ubuntu-latest
     steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: actions/setup-node@v2
       uses: actions/setup-node@v2   
       with:
         node: 16.14
     - run: yarn && yarn jsdoc
     - name: Github-pages artifact
       uses: actions/upload-pages-artifact@v1
       with:
         path: docs
#     - name: Archive production artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: github-pages
#         path: docs
           
   deploy: 
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
 
 
 
