 name: JSDoc to pages
 on: 
   push:
     branches:
       - master

 jobs:
   Build:
     runs-on: ubuntu-latest
     steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: actions/setup-node@v2
       uses: actions/setup-node@v2   
       with:
         node: 16.14
     - run: yarn && yarn jsdoc

   Deploy: 
     needs: Build
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v2
       - name: download build files
         uses: actions/download-artifact@v2
         with:
           name: build-pages
           path: docs
       - name: deploy
         uses: JamesIves/github-pages-deploy-action@v4.2.3
         with:
           branch: gh-pages
           folder: docs 
           token: "${{ secrets.DEPLOY_TOKEN }}"  
